### ISSUE TITLE
how to get AZURE_OPENAI_KEY and AZURE_OPENAI_ENDPOINT

### ISSUE THREAD

**Issue by yaofulan** [microsoft/ChatGPT-Robot-Manipulation-Prompts#8]
(chatRo) csc@csclab:~/ChatGPT-Robot-Manipulation-Prompts/examples/task_decomposition$ python aimodel.py --scenario 'shelf'
Traceback (most recent call last):
  File "/home/csc/ChatGPT-Robot-Manipulation-Prompts/examples/task_decomposition/aimodel.py", line 303, in <module>
    aimodel = ChatGPT(
  File "/home/csc/ChatGPT-Robot-Manipulation-Prompts/examples/task_decomposition/aimodel.py", line 37, in __init__
    openai.api_key = credentials["azureopenai"]["AZURE_OPENAI_KEY"]
KeyError: 'azureopenai'

**Comment by Naoki-Wake** [comment]
Hello yaofulan, to obtain the AZURE_OPENAI_KEY and AZURE_OPENAI_ENDPOINT, you need to set up an active Azure subscription. For detailed instructions on how to set up Azure OpenAI and retrieve the necessary credentials, please refer to the official documentation [here](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/).
